
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import net.proteanit.sql.DbUtils;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author chimmu123
 */
public class database extends javax.swing.JFrame {
static String m;
    /**
     * Creates new form database
     */
    public database(String a) {
        initComponents();
        m=a;
      //  t1.setText(m+" "+"DATABASE");
         Connection connection = null; 
 
String driverName ="oracle.jdbc.driver.OracleDriver"; // for Oracle 
 
 
String serverName = "localhost"; 
String portNumber = "1521"; 
String sid = "home"; 
 
String url="jdbc:oracle:thin:@"+serverName+":"+ portNumber+":"+sid; 

 
String username = "chimmu"; 
String password = "chimmu123"; 
 
 
try { 

 Class.forName(driverName); 
 
 connection = DriverManager.getConnection(url, username, password); 
 
 } catch (ClassNotFoundException e) { 
  
 System.out.println("ClassNotFoundException : "+e.getMessage()); 
 
 } catch (SQLException e) { 

 System.out.println(e.getMessage()); 
 
 } 
try
{
      Statement stmt=null;
    if(m.equals("students"))  
    {
         stmt = connection.createStatement();
    String q2="select * from students1";
    
      ResultSet rs3 = stmt.executeQuery(q2); 
      //rs3.next();
      tb1.setModel(DbUtils.resultSetToTableModel(rs3));
       stmt.close(); 
            }
         else  if(m.equals("payments"))  
    {
         stmt = connection.createStatement();
    String q2="select * from payments";
    
      ResultSet rs3 = stmt.executeQuery(q2); 
      //rs3.next();
      tb1.setModel(DbUtils.resultSetToTableModel(rs3));
       stmt.close(); 
            }
          else  if(m.equals("employee"))  
    {
         stmt = connection.createStatement();
    String q2="select * from employee";
    
      ResultSet rs3 = stmt.executeQuery(q2); 
      //rs3.next();
      tb1.setModel(DbUtils.resultSetToTableModel(rs3));
       stmt.close(); 
            }
    else if(m.equals("status1"))  
    {
         stmt = connection.createStatement();
    String q3="select * from status1";
    
      ResultSet rs4 = stmt.executeQuery(q3); 
     // rs4.next();
      tb1.setModel(DbUtils.resultSetToTableModel(rs4));
       stmt.close(); 
            }
     else if(m.equals("books1"))  
    {
         stmt = connection.createStatement();
    String q3="select * from books1";
    
      ResultSet rs4 = stmt.executeQuery(q3); 
      //rs4.next();
      tb1.setModel(DbUtils.resultSetToTableModel(rs4));
       stmt.close(); 
            }
     else if(m.equals("books2"))  
    {
         stmt = connection.createStatement();
    String q3="select * from books2";
    
      ResultSet rs4 = stmt.executeQuery(q3); 
      //rs4.next();
      tb1.setModel(DbUtils.resultSetToTableModel(rs4));
       stmt.close(); 
            }
    else if(m.equals("fines1"))  
    {
         stmt = connection.createStatement();
    String q3="select * from fines1";
    
      ResultSet rs4 = stmt.executeQuery(q3); 
      //rs4.next();
      tb1.setModel(DbUtils.resultSetToTableModel(rs4));
       stmt.close(); 
            }
    
    
}
catch(SQLException e){System.out.println(e);}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        l1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VIEW DATABASE TABLES\n");

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb1);

        l1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        l1.setText("<HTML>\n<U>VIEW DATABASE TABLES</U>\n</HTML>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(database.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(database.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(database.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(database.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new database(m).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JTable tb1;
    // End of variables declaration//GEN-END:variables
}
