/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author chimmu123
 */
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.*;
import net.proteanit.sql.DbUtils;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

public class inflow extends javax.swing.JFrame {

    /**
     * Creates new form inflow
     */
    public inflow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        l2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        t1 = new com.toedter.calendar.JDateChooser();
        l1 = new javax.swing.JLabel();
        t2 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        t3 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ANALYSIS OF INFLOW OF BOOKS");

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb1);

        l2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        l2.setText("<HTML>\n<U>INFLOW OF BOOKS</U>\n</HTML>");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        t1.setDateFormatString("yyyy-MM-dd");

        l1.setText("Date Range From");

        t2.setDateFormatString("yyyy-MM-dd");

        jLabel1.setText("To");

        b1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b1.setText("OK");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(l1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t2, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(b1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        b2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b2.setText("BARGRAPH");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        t3.setColumns(20);
        t3.setRows(5);
        t3.setWrapStyleWord(true);
        t3.setBorder(null);
        jScrollPane2.setViewportView(t3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(b2)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(b2)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed

       // int days = Days.daysBetween(d1, d2).getDays();// TODO add your handling code here:
         java.sql.Date sqlDate ,sqlDate1;
        
         Connection connection = null; 
 
String driverName ="oracle.jdbc.driver.OracleDriver"; // for Oracle 
 
 
String serverName = "localhost"; 
String portNumber = "1521"; 
String sid = "home"; 
 
String url="jdbc:oracle:thin:@"+serverName+":"+ portNumber+":"+sid; 

 
String username = "chimmu"; 
String password = "chimmu123"; 
 
 
try { 

 Class.forName(driverName); 
 
 connection = DriverManager.getConnection(url, username, password); 
 
 } catch (ClassNotFoundException e) { 
  
 System.out.println("ClassNotFoundException : "+e.getMessage()); 
 
 } catch (SQLException e) { 

 System.out.println(e.getMessage()); 
 
 } 
try
{
     Statement stmt=null;
      stmt = connection.createStatement();
      System.out.println("rough n tough");
      Date d1,d2,d3;
      d1=  t1.getDate();
      System.out.println(d1);
      
      d2=t2.getDate();
        System.out.println(d2);
         if(d1==null ||d2==null)
         {
                System.out.println("hellor eyy!!");
             String q1 ="select sysdate from dual";
               ResultSet r = stmt.executeQuery(q1);
               r.next();
               sqlDate1=r.getDate(1);
                String q2 ="select (sysdate-30) from dual";
               ResultSet r2 = stmt.executeQuery(q2);
               r2.next();
               sqlDate=r2.getDate(1);
               
         }
         else
         {
          sqlDate = new java.sql.Date(d1.getTime());
         System.out.println("sqlDate:" + sqlDate.toString());
         sqlDate1 = new java.sql.Date(d2.getTime());
         System.out.println("sqlDate:" + sqlDate1.toString());
         }
      
      
      
      
      String query = "select bookid,bookname,rdate from inflow2 where rdate between (select to_date('"+sqlDate+"','YYYY-MM-DD') from dual) and (select to_date('"+sqlDate1+"','YYYY-MM-DD') from dual) ";
      ResultSet rs = stmt.executeQuery(query); 
    /*  if(rs.next()==false)
      {
          t3.setText("SORRY NO TRANSACATION HAS TAKEN PLACE IN BETWEEN SELECTED DATES");
      }*/
       
      // System.out.println(rs.next());
       //System.out.println("rough");
      //System.out.println(""+rs.getInt(1));
      // System.out.println(rs.first());
    /*  while(rs.next())
      {
          //System.out.println(rs.first());
      System.out.println("rough");
       System.out.println(rs.getInt(1));
      }*/
    //   System.out.println("rough");
      tb1.setModel(DbUtils.resultSetToTableModel(rs));
       String query1 = "select bookid,bookname,rdate from inflow2 where rdate between (select to_date('"+sqlDate+"','YYYY-MM-DD') from dual) and (select to_date('"+sqlDate1+"','YYYY-MM-DD') from dual) ";
      ResultSet rs1 = stmt.executeQuery(query1);
       if(rs1.next()==false)
      {
           
          t3.setText("SORRY NO TRANSACATION HAS TAKEN PLACE IN BETWEEN SELECTED DATES");
      }
     /* while(rs.next()){
            System.out.println(rs.getString(2));
      }
      System.out.println(rs.getString(2));*/
      stmt.close();
}
catch(SQLException e){System.out.println(e);}
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
    
       // int days = Days.daysBetween(d1, d2).getDays();// TODO add your handling code here:
         java.sql.Date sqlDate,sqlDate1;
           Connection connection = null; 
String driverName ="oracle.jdbc.driver.OracleDriver"; // for Oracle 
 
 
String serverName = "localhost"; 
String portNumber = "1521"; 
String sid = "home"; 
 
String url="jdbc:oracle:thin:@"+serverName+":"+ portNumber+":"+sid; 

 
String username = "chimmu"; 
String password = "chimmu123"; 
 
 
try { 

 Class.forName(driverName); 
 
 connection = DriverManager.getConnection(url, username, password); 
 
 } catch (ClassNotFoundException e) { 
  
 System.out.println("ClassNotFoundException : "+e.getMessage()); 
 
 } catch (SQLException e) { 

 System.out.println(e.getMessage()); 
 
 } 
try
{
     Statement stmt=null;
      stmt = connection.createStatement();
         System.out.println("hhiiiii");
         Date d1,d2,d3,f;
      d1=  t1.getDate();
      System.out.println(d1);
      int y=0;
     // String f="";
      d2=t2.getDate();
        System.out.println(d2);
         if(d1==null ||d2==null)
         {
                System.out.println("hellor eyy!!");
             String q1 ="select sysdate from dual";
               ResultSet r = stmt.executeQuery(q1);
               r.next();
               sqlDate1=r.getDate(1);
                String q2 ="select (sysdate-30) from dual";
               ResultSet r2 = stmt.executeQuery(q2);
               r2.next();
               sqlDate=r2.getDate(1);
               
         }
         else
         {
          sqlDate = new java.sql.Date(d1.getTime());
         System.out.println("sqlDate:" + sqlDate.toString());
         sqlDate1 = new java.sql.Date(d2.getTime());
         System.out.println("sqlDate:" + sqlDate1.toString());
         }
        String query = "select count(bookid),rdate from inflow2\n" +
"group by rdate\n" +
"having rdate between ( select to_date('"+sqlDate+"','YYYY-MM-DD') from dual) and (select to_date('"+sqlDate1+"','YYYY-MM-DD') from dual)" ; 
     ResultSet rs = stmt.executeQuery(query);
    /*  if(rs.next()==false)
      {
          t3.setText("SORRY NO TRANSACATION HAS TAKEN PLACE IN BETWEEN SELECTED DATES");
      }*/
      System.out.println("checkingg here");
        DefaultCategoryDataset dataset=new DefaultCategoryDataset();
        while(rs.next())
        {
             System.out.println("helloo");
            f=rs.getDate(2);
            y=rs.getInt(1);
            dataset.setValue(y,"no of buks",f);
        }
      /* dataset.setValue(78, "Marks", "s2");
       dataset.setValue(20, "Marks", "s3");*/
       //dataset.setValue(40, "Marks", "s4");
       JFreeChart chart= ChartFactory.createBarChart("INFLOW ANALYSIS","DATE","NO. OF BOOKS",dataset,PlotOrientation.VERTICAL,false,true,false);
       CategoryPlot p=chart.getCategoryPlot();
       p.setRangeGridlinePaint(Color.black);
       ChartFrame frame=new ChartFrame("bargraph",chart);
       frame.setVisible(true);
       frame.setSize(450,350);
         String query1 = "select count(bookid),rdate from inflow2\n" +
"group by rdate\n" +
"having rdate between ( select to_date('"+sqlDate+"','YYYY-MM-DD') from dual) and (select to_date('"+sqlDate1+"','YYYY-MM-DD') from dual)" ; 
     ResultSet rs1 = stmt.executeQuery(query1);
      if(rs1.next()==false)
      {
          t3.setText("SORRY NO TRANSACATION HAS TAKEN PLACE IN BETWEEN SELECTED DATES");
      }
}
catch(SQLException e){System.out.println(e);}
// TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inflow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inflow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inflow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inflow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inflow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private com.toedter.calendar.JDateChooser t1;
    private com.toedter.calendar.JDateChooser t2;
    private javax.swing.JTextArea t3;
    private javax.swing.JTable tb1;
    // End of variables declaration//GEN-END:variables
}
