--------------------------------------------------------
--  File created - Sunday-February-02-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PAYMENTS
--------------------------------------------------------

  CREATE TABLE "CHIMMU"."PAYMENTS" 
   (	"ID" VARCHAR2(30 BYTE), 
	"BOOKID" NUMBER, 
	"RECEIPTID" NUMBER, 
	"AMT" NUMBER, 
	"PDATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PAYMENTS1
--------------------------------------------------------

  CREATE TABLE "CHIMMU"."PAYMENTS1" 
   (	"ID" VARCHAR2(30 BYTE), 
	"BOOKID" NUMBER, 
	"RECEIPTID" NUMBER, 
	"AMT" NUMBER, 
	"PDATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PAYMENTS2
--------------------------------------------------------

  CREATE TABLE "CHIMMU"."PAYMENTS2" 
   (	"ID" VARCHAR2(30 BYTE), 
	"BOOKID" NUMBER, 
	"RECEIPTID" NUMBER, 
	"AMT" NUMBER, 
	"PDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into CHIMMU.PAYMENTS
SET DEFINE OFF;
REM INSERTING into CHIMMU.PAYMENTS1
SET DEFINE OFF;
REM INSERTING into CHIMMU.PAYMENTS2
SET DEFINE OFF;
Insert into CHIMMU.PAYMENTS2 (ID,BOOKID,RECEIPTID,AMT,PDATE) values ('160111733051',110,1551,35,to_date('10-JAN-14','DD-MON-RR'));
Insert into CHIMMU.PAYMENTS2 (ID,BOOKID,RECEIPTID,AMT,PDATE) values ('160111733051',121,1659,35,to_date('10-JAN-14','DD-MON-RR'));
Insert into CHIMMU.PAYMENTS2 (ID,BOOKID,RECEIPTID,AMT,PDATE) values ('160110734044',136,1790,15,to_date('10-JAN-14','DD-MON-RR'));
Insert into CHIMMU.PAYMENTS2 (ID,BOOKID,RECEIPTID,AMT,PDATE) values ('160110734044',138,1790,45,to_date('14-JAN-14','DD-MON-RR'));
Insert into CHIMMU.PAYMENTS2 (ID,BOOKID,RECEIPTID,AMT,PDATE) values ('160111733034',100,1975,80,to_date('12-JAN-14','DD-MON-RR'));
Insert into CHIMMU.PAYMENTS2 (ID,BOOKID,RECEIPTID,AMT,PDATE) values ('160111733034',152,1765,120,to_date('13-JAN-14','DD-MON-RR'));
